permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

filter: 'category'

# 作者信息
author: 
  name: ZenMoore
  email: wzk1057398161@qq.com
  zhihu: https://www.zhihu.com/people/ZenMoore
  github: https://github.com/ZenMoore
  Sina Weibo: http://weibo.com/JavcMak
  Sourceforge: http://sourceforge.net/zenmoo

# 站点信息
title: Pokecub
description: 斗志昂扬，七三最强
url: https://pokecub573.github.io/
email: wzk1057398161@qq.com
github: Pokecub-573
# rss_url: /pages/atom.xml

# Social account
# twitter:  username
# weibo:    JavcMak
github:   Pokecub-573
# codepen:  username
# dribbble: username

# avatar头像及Favicon
avatar: /assets/img/avatar.jpg
favicon: /assets/img/favicon.ico

sass:
  style: compressed
gems:
  - jekyll-sitemap
